deployment:
  tasks:
    - export DEPLOYPATH=/home/omni/nodeapps/omniServiceBackend/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && pm2 restart omniServiceBackend || pm2 start app.js --name omniServiceBackend
